version: 2
      
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - circleci-integration
    docker:
      - image: docker:edge-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Make docker image
          command: |
            export REV=$(git rev-parse --short HEAD)
            docker build -t zypeh/purelude:$REV -t zypeh/purelude:$CIRCLE_BRANCH -t zypeh/purelude:latest .
