version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:unstable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Make docker image
          command: |
            export REV=$(git rev-parse --short HEAD)
            docker build -t zypeh/purelude:$REV -t zypeh/purelude:$CIRCLE_BRANCH -t zypeh/purelude:latest .